ADD: Missing DFL intel-m10-bmc-retimer driver from Xu Yilun, 2020
WIP: The driver does not show linkstatus, retimer versions

Error: fpgainfo uses direct hacking on the regmap for SPI, which requires
root access.
This driver could potential fix that issue.

Moved the driver to FPGA and tried my best to fix issues due to old patch.